/**
 * PRJ-016 HANEI - W2 シード問題プール（第1陣 200 問）
 *
 * 作成日: 2026-04-26
 * 作成部署: Research（W2）
 * 範囲: 英検 5級 / 4級 / 3級
 * 内訳:
 *   - 5級 vocab: 60 問（V5-001 〜 V5-060）
 *   - 5級 grammar: 30 問（G5-001 〜 G5-030）
 *   - 4級 vocab: 50 問（V4-001 〜 V4-050）
 *   - 4級 listening-response: 20 問（L4-001 〜 L4-020）
 *   - 3級 vocab: 30 問（V3-001 〜 V3-030）
 *   - 3級 reading: 10 問（R3-001 〜 R3-010）
 *
 * 制約:
 *   - 100% オリジナル（過去問流用なし）
 *   - 絵文字なし
 *   - 子ども不適切表現なし
 *   - 固有名詞は架空（学校名 = "Sakura Elementary"、街名 = "Hanei Town"）
 *
 * 注: 型定義 `Problem` は Dev 部署が schema-types.ts に追加予定。
 * 暫定的にローカル型を定義しておき、Dev の型定義が出来たら import 切り替え。
 */

// import type { Problem } from '../src/lib/db/schema-types';
// 暫定ローカル型（Dev 部署 schema-types.ts 完成後に置き換え）
type Problem = {
  level: 'eiken-5' | 'eiken-4' | 'eiken-3';
  skill: 'vocab' | 'grammar' | 'listening-response' | 'reading';
  prompt_text: string;
  passage_text?: string;
  choices: string[];
  correct_index: number;
  explanation_jp: string;
  difficulty: 0 | 1 | 2;
  estimated_time_sec: number;
  tags: string[];
  audio_transcript?: string;
  copyright_safe: true;
  generated_quality_score: number;
};

const problems: Problem[] = [
  // ============================================================
  // 5級 vocab 60 問（V5-001 〜 V5-060）
  // 範囲: be 動詞、一般動詞、基本名詞（家族・学校・食べ物・動物・色・数）、基本形容詞
  // ============================================================

  // V5-001 be 動詞 am
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I (   ) a student.',
    choices: ['am', 'is', 'are', 'be'],
    correct_index: 0,
    explanation_jp: '「I」のあとには「am」を使います。「I am a student.」で「わたしは学生です」という意味になります。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['be-verb', 'pronoun-i'],
    copyright_safe: true,
    generated_quality_score: 0.94,
  },
  // V5-002 be 動詞 is
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'This (   ) my dog.',
    choices: ['am', 'is', 'are', 'do'],
    correct_index: 1,
    explanation_jp: '「This」のあとには「is」を使います。「This is my dog.」で「これはわたしの犬です」という意味になります。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['be-verb', 'this'],
    copyright_safe: true,
    generated_quality_score: 0.94,
  },
  // V5-003 be 動詞 are
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'You (   ) very kind.',
    choices: ['am', 'is', 'are', 'do'],
    correct_index: 2,
    explanation_jp: '「You」のあとには「are」を使います。「You are very kind.」で「あなたはとてもやさしい」という意味になります。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['be-verb', 'pronoun-you'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-004 一般動詞 like
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I (   ) apples very much.',
    choices: ['like', 'see', 'go', 'play'],
    correct_index: 0,
    explanation_jp: '「〜が好き」は「like」を使います。「I like apples.」で「わたしはりんごが好きです」という意味です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['verb-like', 'food'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-005 一般動詞 play
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'Ben and Tom (   ) soccer after school.',
    choices: ['eat', 'play', 'read', 'sleep'],
    correct_index: 1,
    explanation_jp: 'スポーツをするは「play」を使います。「play soccer」でサッカーをするという意味です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['verb-play', 'sports'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-006 一般動詞 go
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I (   ) to school every day.',
    choices: ['go', 'see', 'have', 'come'],
    correct_index: 0,
    explanation_jp: '「〜へ行く」は「go to」を使います。「go to school」で学校へ行くという意味です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['verb-go', 'school'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-007 一般動詞 eat
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'We (   ) breakfast at seven.',
    choices: ['eat', 'play', 'sing', 'walk'],
    correct_index: 0,
    explanation_jp: '食事をとるは「eat」を使います。「eat breakfast」で朝ごはんを食べるという意味です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['verb-eat', 'meal'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-008 一般動詞 see
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I can (   ) a big bird in the tree.',
    choices: ['see', 'eat', 'do', 'go'],
    correct_index: 0,
    explanation_jp: '「見える」は「see」を使います。意識せずに目に入るときは「see」がよく使われます。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['verb-see', 'animal'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-009 一般動詞 have
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I (   ) two cats at home.',
    choices: ['have', 'play', 'go', 'read'],
    correct_index: 0,
    explanation_jp: '「〜を持っている、飼っている」は「have」を使います。「have a pet」でペットを飼っているという意味です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['verb-have', 'animal'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-010 一般動詞 read
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'Lily (   ) a book in her room.',
    choices: ['reads', 'eats', 'sings', 'runs'],
    correct_index: 0,
    explanation_jp: '本を読むは「read」を使います。主語が Lily なので s をつけて「reads」になります。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['verb-read', 'third-person-s'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V5-011 名詞 family - mother
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'My (   ) cooks dinner every evening.',
    choices: ['mother', 'pencil', 'apple', 'window'],
    correct_index: 0,
    explanation_jp: '「mother」はお母さんという意味です。料理をする家族の人として最も自然な答えです。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-family', 'mother'],
    copyright_safe: true,
    generated_quality_score: 0.94,
  },
  // V5-012 名詞 family - father
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'My (   ) drives a car to work.',
    choices: ['father', 'apple', 'desk', 'dog'],
    correct_index: 0,
    explanation_jp: '「father」はお父さんという意味です。仕事に車で行くという文脈に合います。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-family', 'father'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-013 名詞 family - sister
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'My (   ) is ten years old. She is in the fifth grade.',
    choices: ['sister', 'school', 'pencil', 'orange'],
    correct_index: 0,
    explanation_jp: '「sister」は姉や妹という意味です。「She」という代名詞からも女の人だとわかります。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['noun-family', 'sister'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-014 名詞 family - brother
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'My (   ) plays the piano every day. He is good at music.',
    choices: ['brother', 'desk', 'ball', 'milk'],
    correct_index: 0,
    explanation_jp: '「brother」は兄や弟という意味です。「He」という代名詞から男の人だとわかります。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['noun-family', 'brother'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-015 名詞 school - teacher
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'Ms. Green is my English (   ).',
    choices: ['teacher', 'apple', 'window', 'bird'],
    correct_index: 0,
    explanation_jp: '「teacher」は先生という意味です。Ms. Green が英語を教える人なので「teacher」が答えです。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-school', 'teacher'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-016 名詞 school - student
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I am a (   ) at Sakura Elementary.',
    choices: ['student', 'cat', 'book', 'milk'],
    correct_index: 0,
    explanation_jp: '「student」は生徒という意味です。学校に通う人を表します。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-school', 'student'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-017 名詞 school - book
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I read a (   ) before bed.',
    choices: ['book', 'soup', 'tree', 'rain'],
    correct_index: 0,
    explanation_jp: '「book」は本という意味です。「read a book」で本を読むという定番の表現です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-school', 'book'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-018 名詞 school - pencil
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I write with a (   ) in my notebook.',
    choices: ['pencil', 'banana', 'cat', 'door'],
    correct_index: 0,
    explanation_jp: '「pencil」はえんぴつという意味です。書くために使う道具です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-school', 'pencil'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-019 名詞 food - apple
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'An (   ) is a sweet red fruit.',
    choices: ['apple', 'eraser', 'umbrella', 'octopus'],
    correct_index: 0,
    explanation_jp: '「apple」はりんごという意味です。あまくて赤い果物です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-food', 'fruit'],
    copyright_safe: true,
    generated_quality_score: 0.94,
  },
  // V5-020 名詞 food - milk
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I drink (   ) every morning.',
    choices: ['milk', 'pencil', 'desk', 'tree'],
    correct_index: 0,
    explanation_jp: '「milk」はぎゅうにゅうです。飲み物として最も自然な答えです。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-food', 'drink'],
    copyright_safe: true,
    generated_quality_score: 0.94,
  },
  // V5-021 名詞 food - bread
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I eat (   ) for breakfast.',
    choices: ['bread', 'window', 'rain', 'paper'],
    correct_index: 0,
    explanation_jp: '「bread」はパンという意味です。朝ごはんによく食べる食べ物です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-food', 'breakfast'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-022 名詞 food - rice
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'My family eats (   ) for dinner.',
    choices: ['rice', 'pencil', 'ball', 'shoe'],
    correct_index: 0,
    explanation_jp: '「rice」はお米やごはんという意味です。日本の家庭でよく食べられる主食です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-food', 'staple'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-023 名詞 animal - dog
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'My (   ) likes to run in the park.',
    choices: ['dog', 'pen', 'apple', 'book'],
    correct_index: 0,
    explanation_jp: '「dog」は犬という意味です。公園で走るのは犬として最も自然です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-animal', 'dog'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-024 名詞 animal - cat
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'My (   ) sleeps on the sofa.',
    choices: ['cat', 'milk', 'desk', 'bag'],
    correct_index: 0,
    explanation_jp: '「cat」はネコという意味です。ソファで寝るペットとして自然です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-animal', 'cat'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-025 名詞 animal - bird
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'A small (   ) is singing in the tree.',
    choices: ['bird', 'pencil', 'cup', 'shoe'],
    correct_index: 0,
    explanation_jp: '「bird」は鳥です。木の上で歌うのは鳥として自然な答えです。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-animal', 'bird'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-026 名詞 animal - fish
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'A (   ) lives in the water.',
    choices: ['fish', 'book', 'desk', 'door'],
    correct_index: 0,
    explanation_jp: '「fish」は魚です。水の中に住むのは魚です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['noun-animal', 'fish'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-027 名詞 color - red
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'A tomato is (   ).',
    choices: ['red', 'big', 'old', 'tall'],
    correct_index: 0,
    explanation_jp: '「red」は赤という色です。トマトの色は赤です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['adjective-color', 'red'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-028 名詞 color - blue
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'The sky is (   ) today.',
    choices: ['blue', 'cold', 'fast', 'short'],
    correct_index: 0,
    explanation_jp: '「blue」は青という色です。晴れた空の色です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['adjective-color', 'blue'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-029 名詞 color - green
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'The leaves of the tree are (   ).',
    choices: ['green', 'long', 'old', 'fast'],
    correct_index: 0,
    explanation_jp: '「green」はみどり色です。木の葉は緑色です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['adjective-color', 'green'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-030 名詞 color - white
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'Snow is (   ) and cold.',
    choices: ['white', 'tall', 'happy', 'old'],
    correct_index: 0,
    explanation_jp: '「white」は白という色です。雪は白くて冷たいです。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['adjective-color', 'white'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-031 形容詞 big
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'An elephant is a (   ) animal.',
    choices: ['big', 'small', 'short', 'cold'],
    correct_index: 0,
    explanation_jp: '「big」は大きいという意味です。象はとても大きい動物です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['adjective-size', 'big'],
    copyright_safe: true,
    generated_quality_score: 0.94,
  },
  // V5-032 形容詞 small
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'A mouse is a (   ) animal.',
    choices: ['small', 'tall', 'long', 'fast'],
    correct_index: 0,
    explanation_jp: '「small」は小さいという意味です。ねずみは小さい動物です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['adjective-size', 'small'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-033 形容詞 hot
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'It is very (   ) in summer.',
    choices: ['hot', 'cold', 'tall', 'old'],
    correct_index: 0,
    explanation_jp: '「hot」は暑いという意味です。夏は暑いという表現です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['adjective-temperature', 'hot'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-034 形容詞 cold
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'It is (   ) in winter.',
    choices: ['cold', 'hot', 'long', 'happy'],
    correct_index: 0,
    explanation_jp: '「cold」は寒いという意味です。冬は寒いという表現です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['adjective-temperature', 'cold'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-035 形容詞 happy
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I am (   ) when I see my friends.',
    choices: ['happy', 'old', 'fast', 'tall'],
    correct_index: 0,
    explanation_jp: '「happy」はうれしいという意味です。友達に会うとうれしいという気持ちを表します。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['adjective-emotion', 'happy'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-036 形容詞 new
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I have a (   ) bag. I bought it yesterday.',
    choices: ['new', 'cold', 'fast', 'short'],
    correct_index: 0,
    explanation_jp: '「new」は新しいという意味です。昨日買ったのだから新しいかばんです。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['adjective-new', 'shopping'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-037 形容詞 old
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'My grandfather is (   ). He is 80 years old.',
    choices: ['old', 'new', 'fast', 'cold'],
    correct_index: 0,
    explanation_jp: '「old」は年を取っているという意味です。80才なので「old」が答えです。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['adjective-age', 'old'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-038 数 one
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I have (   ) brother. His name is Ken.',
    choices: ['one', 'three', 'five', 'ten'],
    correct_index: 0,
    explanation_jp: '「one」は1という意味です。兄か弟が一人いるので「one brother」です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['number', 'one'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-039 数 two
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'A cat has (   ) eyes.',
    choices: ['two', 'four', 'eight', 'ten'],
    correct_index: 0,
    explanation_jp: '「two」は2という意味です。ネコの目は2つです。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['number', 'two'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V5-040 曜日 Monday
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'The day after Sunday is (   ).',
    choices: ['Monday', 'Friday', 'Saturday', 'Wednesday'],
    correct_index: 0,
    explanation_jp: '日曜日の次の日は月曜日です。「Monday」は月曜日です。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['day', 'monday'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-041 曜日 Sunday
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I do not go to school on (   ). I stay at home.',
    choices: ['Sunday', 'Monday', 'Tuesday', 'Friday'],
    correct_index: 0,
    explanation_jp: '「Sunday」は日曜日です。学校に行かない日は日曜日です。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['day', 'sunday'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V5-042 月 January
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: '(   ) is the first month of the year.',
    choices: ['January', 'July', 'May', 'October'],
    correct_index: 0,
    explanation_jp: '「January」は1月です。1年の最初の月は1月です。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['month', 'january'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-043 月 December
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: '(   ) is the last month of the year.',
    choices: ['December', 'April', 'June', 'August'],
    correct_index: 0,
    explanation_jp: '「December」は12月です。1年の最後の月は12月です。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['month', 'december'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V5-044 季節 summer
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'We swim in the sea in (   ).',
    choices: ['summer', 'winter', 'spring', 'autumn'],
    correct_index: 0,
    explanation_jp: '「summer」は夏です。海で泳ぐのは夏が一番自然です。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['season', 'summer'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-045 季節 winter
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'We see snow in (   ).',
    choices: ['winter', 'summer', 'spring', 'autumn'],
    correct_index: 0,
    explanation_jp: '「winter」は冬です。雪が見られるのは冬です。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['season', 'winter'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-046 一般動詞 sing
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I (   ) a song in music class.',
    choices: ['sing', 'eat', 'go', 'have'],
    correct_index: 0,
    explanation_jp: '歌を歌うは「sing」を使います。「sing a song」で歌を歌うという意味です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['verb-sing', 'music'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-047 一般動詞 run
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I (   ) in the park every morning.',
    choices: ['run', 'eat', 'read', 'sleep'],
    correct_index: 0,
    explanation_jp: '走るは「run」を使います。公園で毎朝走るという表現です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['verb-run', 'exercise'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-048 一般動詞 walk
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I (   ) to school with my friend.',
    choices: ['walk', 'read', 'sing', 'eat'],
    correct_index: 0,
    explanation_jp: '歩くは「walk」を使います。「walk to school」で学校まで歩くという意味です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['verb-walk', 'school'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-049 一般動詞 swim
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'Fish can (   ) very well.',
    choices: ['swim', 'walk', 'read', 'sing'],
    correct_index: 0,
    explanation_jp: '泳ぐは「swim」を使います。魚は泳ぐのが得意です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['verb-swim', 'animal'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-050 一般動詞 study
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I (   ) English every day.',
    choices: ['study', 'eat', 'sing', 'walk'],
    correct_index: 0,
    explanation_jp: '勉強するは「study」を使います。「study English」で英語を勉強するという意味です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['verb-study', 'school'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-051 名詞 weather - rainy
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'It is (   ) today. Take your umbrella.',
    choices: ['rainy', 'sunny', 'happy', 'big'],
    correct_index: 0,
    explanation_jp: '「rainy」は雨が降っているという意味です。傘を持っていくと言っているので雨です。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['weather', 'rainy'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-052 名詞 weather - sunny
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'It is (   ) today. The sky is blue.',
    choices: ['sunny', 'rainy', 'cold', 'old'],
    correct_index: 0,
    explanation_jp: '「sunny」は晴れているという意味です。空が青いので晴れです。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['weather', 'sunny'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-053 名詞 body - hand
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I wash my (   ) before lunch.',
    choices: ['hands', 'shoes', 'desks', 'books'],
    correct_index: 0,
    explanation_jp: '「hands」は手という意味です。昼ごはんの前に手を洗うのが自然です。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['noun-body', 'hand'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-054 名詞 body - eye
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I see with my (   ).',
    choices: ['eyes', 'shoes', 'books', 'pencils'],
    correct_index: 0,
    explanation_jp: '「eyes」は目という意味です。目で見るので「eyes」が答えです。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['noun-body', 'eye'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-055 名詞 sport - baseball
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I play (   ) with my team after school.',
    choices: ['baseball', 'apple', 'pencil', 'water'],
    correct_index: 0,
    explanation_jp: '「baseball」は野球です。チームでするスポーツとして自然です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['sport', 'baseball'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-056 名詞 sport - tennis
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I play (   ) with my sister on Sundays.',
    choices: ['tennis', 'soup', 'window', 'door'],
    correct_index: 0,
    explanation_jp: '「tennis」はテニスです。「play tennis」でテニスをするという意味です。',
    difficulty: 0,
    estimated_time_sec: 20,
    tags: ['sport', 'tennis'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-057 一般動詞 like + ing
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I like (   ) books in my room.',
    choices: ['reading', 'read', 'reads', 'to reads'],
    correct_index: 0,
    explanation_jp: '「like 〜ing」で「〜することが好き」です。「like reading」で読書が好きという意味です。',
    difficulty: 2,
    estimated_time_sec: 30,
    tags: ['verb-like', 'gerund'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V5-058 一般動詞 want
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I (   ) a new bike for my birthday.',
    choices: ['want', 'see', 'go', 'have'],
    correct_index: 0,
    explanation_jp: '「want」はほしいという意味です。誕生日にほしいものを表すときに使います。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['verb-want', 'birthday'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V5-059 名詞 hobby - music
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'I listen to (   ) every night.',
    choices: ['music', 'apple', 'shoes', 'pencil'],
    correct_index: 0,
    explanation_jp: '「music」は音楽です。「listen to music」で音楽を聴くという意味です。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['hobby', 'music'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V5-060 形容詞 nice
  {
    level: 'eiken-5',
    skill: 'vocab',
    prompt_text: 'Mary is a (   ) friend. She is kind to me.',
    choices: ['nice', 'old', 'fast', 'short'],
    correct_index: 0,
    explanation_jp: '「nice」はすてきな、よいという意味です。やさしい友達を表すのにぴったりの言葉です。',
    difficulty: 1,
    estimated_time_sec: 25,
    tags: ['adjective-personality', 'nice'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },

  // ============================================================
  // 5級 grammar 30 問（G5-001 〜 G5-030）
  // 範囲: be 動詞 / 一般動詞 / 疑問文 / 否定文
  // ============================================================

  // G5-001 be 動詞 否定形
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'I (   ) a teacher. I am a student.',
    choices: ['am not', 'is not', 'are not', 'do not'],
    correct_index: 0,
    explanation_jp: '「I」のあとは「am」を使います。否定文は「am not」になります。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['be-verb', 'negative'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // G5-002 be 動詞 疑問文
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: '(   ) you a student of Sakura Elementary?',
    choices: ['Are', 'Is', 'Am', 'Do'],
    correct_index: 0,
    explanation_jp: '「you」のとき be 動詞は「are」を使います。疑問文では「Are」を文の先頭に置きます。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['be-verb', 'question'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // G5-003 一般動詞 否定形
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'I (   ) like carrots.',
    choices: ['do not', 'am not', 'is not', 'does not'],
    correct_index: 0,
    explanation_jp: '一般動詞の否定文は「do not (don\'t)」を使います。「I」のときは「do not」です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['general-verb', 'negative'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // G5-004 一般動詞 疑問文
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: '(   ) you play soccer?',
    choices: ['Do', 'Are', 'Is', 'Does'],
    correct_index: 0,
    explanation_jp: '一般動詞の疑問文は「Do」を文の先頭に置きます。「you」のときは「Do」を使います。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['general-verb', 'question'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // G5-005 三人称単数 does
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: '(   ) Lily play the piano?',
    choices: ['Does', 'Do', 'Is', 'Are'],
    correct_index: 0,
    explanation_jp: '主語が Lily（三人称単数）のとき、疑問文は「Does」を使います。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['third-person-s', 'question'],
    copyright_safe: true,
    generated_quality_score: 0.89,
  },
  // G5-006 三人称単数の s
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'Tom (   ) breakfast at seven.',
    choices: ['eats', 'eat', 'eating', 'is eat'],
    correct_index: 0,
    explanation_jp: '主語が Tom（三人称単数）で現在のことなので、動詞に s をつけて「eats」です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['third-person-s'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // G5-007 What 疑問文
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'A: (   ) is this? B: It is a pencil.',
    choices: ['What', 'Where', 'Who', 'When'],
    correct_index: 0,
    explanation_jp: '「これは何ですか？」とものを聞くときは「What」を使います。答えが「えんぴつです」なので What が答えです。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['wh-question', 'what'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // G5-008 Where 疑問文
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'A: (   ) is my bag? B: It is on the desk.',
    choices: ['Where', 'What', 'When', 'How'],
    correct_index: 0,
    explanation_jp: '場所を聞くときは「Where」を使います。「on the desk」と場所を答えています。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['wh-question', 'where'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // G5-009 Who 疑問文
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'A: (   ) is that boy? B: He is my brother.',
    choices: ['Who', 'What', 'Where', 'When'],
    correct_index: 0,
    explanation_jp: '人を聞くときは「Who」を使います。「my brother」と人を答えています。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['wh-question', 'who'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // G5-010 When 疑問文
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'A: (   ) is your birthday? B: It is in May.',
    choices: ['When', 'Where', 'Who', 'What'],
    correct_index: 0,
    explanation_jp: '時を聞くときは「When」を使います。「in May」と月を答えています。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['wh-question', 'when'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // G5-011 代名詞 he
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'This is Ben. (   ) is my friend.',
    choices: ['He', 'She', 'It', 'They'],
    correct_index: 0,
    explanation_jp: 'Ben は男の子なので、代名詞は「He」（彼）を使います。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['pronoun', 'he'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // G5-012 代名詞 she
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'This is Mary. (   ) is from Hanei Town.',
    choices: ['She', 'He', 'It', 'They'],
    correct_index: 0,
    explanation_jp: 'Mary は女の子なので、代名詞は「She」（彼女）を使います。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['pronoun', 'she'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // G5-013 代名詞 it
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'I have a cat. (   ) is white and small.',
    choices: ['It', 'He', 'She', 'They'],
    correct_index: 0,
    explanation_jp: '動物やものは「It」（それ）で受けます。「cat」を「It」で受けています。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['pronoun', 'it'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // G5-014 所有格 my
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'This is (   ) book. I read it every night.',
    choices: ['my', 'I', 'me', 'mine'],
    correct_index: 0,
    explanation_jp: '名詞 (book) の前に置いて「わたしの」というときは「my」を使います。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['possessive', 'my'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // G5-015 所有格 your
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'Is this (   ) pencil?',
    choices: ['your', 'you', 'yours', 'yourself'],
    correct_index: 0,
    explanation_jp: '名詞の前に置いて「あなたの」というときは「your」を使います。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['possessive', 'your'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // G5-016 a / an
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'I have (   ) apple in my bag.',
    choices: ['an', 'a', 'the', 'one'],
    correct_index: 0,
    explanation_jp: '母音 (a, i, u, e, o) の音で始まる語の前は「an」を使います。「apple」は a の音で始まります。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['article', 'an'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // G5-017 a / an
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'I see (   ) dog in the park.',
    choices: ['a', 'an', 'the', 'one'],
    correct_index: 0,
    explanation_jp: '母音以外の音で始まる語の前は「a」を使います。「dog」は d の音で始まります。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['article', 'a'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // G5-018 命令文
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: '(   ) the door, please.',
    choices: ['Open', 'Opens', 'Opening', 'To open'],
    correct_index: 0,
    explanation_jp: '命令文は動詞の原形ではじめます。「Open the door」でドアを開けてください、です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['imperative'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // G5-019 Let's
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: '(   ) play soccer in the park!',
    choices: ["Let's", 'We are', 'I am', 'You are'],
    correct_index: 0,
    explanation_jp: '「〜しよう」と人をさそうときは「Let\'s」を使います。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['lets'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // G5-020 can
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'I (   ) swim in the river.',
    choices: ['can', 'am', 'do', 'is'],
    correct_index: 0,
    explanation_jp: '「〜できる」は「can」を使います。「can swim」で泳げるという意味です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['modal', 'can'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // G5-021 can 否定
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'My little brother (   ) read English yet.',
    choices: ['cannot', 'is not', 'do not', 'does not'],
    correct_index: 0,
    explanation_jp: 'can の否定形は「cannot (can\'t)」です。「英語をまだ読めない」という意味です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['modal', 'cannot'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // G5-022 can 疑問
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: '(   ) you play the piano?',
    choices: ['Can', 'Are', 'Is', 'Do'],
    correct_index: 0,
    explanation_jp: '「〜できますか」と聞くときは「Can」を文の先頭に置きます。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['modal', 'can-question'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // G5-023 複数形 -s
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'I have three (   ) at home.',
    choices: ['cats', 'cat', 'a cat', 'caties'],
    correct_index: 0,
    explanation_jp: '2つ以上のものは複数形にします。cat の複数形は s をつけて「cats」です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['plural'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // G5-024 複数形 -es
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'There are two (   ) on the table.',
    choices: ['boxes', 'boxs', 'box', 'boxies'],
    correct_index: 0,
    explanation_jp: 'x で終わる名詞の複数形は es をつけます。box の複数形は「boxes」です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['plural', 'es-ending'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // G5-025 前置詞 in
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'My pen is (   ) the pencil case.',
    choices: ['in', 'on', 'under', 'at'],
    correct_index: 0,
    explanation_jp: '「〜の中に」は「in」を使います。ペンケースの中にペンがあります。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['preposition', 'in'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // G5-026 前置詞 on
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'The book is (   ) the desk.',
    choices: ['on', 'in', 'under', 'with'],
    correct_index: 0,
    explanation_jp: '「〜の上に」は「on」を使います。机の上に本があります。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['preposition', 'on'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // G5-027 前置詞 under
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'My cat is (   ) the chair.',
    choices: ['under', 'in', 'with', 'on'],
    correct_index: 0,
    explanation_jp: '「〜の下に」は「under」を使います。いすの下にネコがいます。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['preposition', 'under'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // G5-028 How many
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'A: (   ) books do you have? B: I have ten.',
    choices: ['How many', 'How much', 'How', 'What'],
    correct_index: 0,
    explanation_jp: '数を聞くときは「How many」を使います。本の数を聞いています。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['wh-question', 'how-many'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // G5-029 What time
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'A: (   ) time is it? B: It is three o\'clock.',
    choices: ['What', 'How', 'When', 'Where'],
    correct_index: 0,
    explanation_jp: '時刻を聞くときは「What time」を使います。3時と時刻を答えています。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['wh-question', 'what-time'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // G5-030 三人称単数 doesn't
  {
    level: 'eiken-5',
    skill: 'grammar',
    prompt_text: 'Mike (   ) like natto.',
    choices: ["doesn't", "don't", 'is not', 'are not'],
    correct_index: 0,
    explanation_jp: '主語が Mike（三人称単数）の一般動詞の否定文は「doesn\'t」を使います。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['third-person-s', 'negative'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },

  // ============================================================
  // 4級 vocab 50 問（V4-001 〜 V4-050）
  // 範囲: 基本動詞拡張 + 学校生活 / 家族 / 食べ物 名詞
  // ============================================================

  // V4-001 動詞 enjoy
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I (   ) playing with my brother on weekends.',
    choices: ['enjoy', 'eat', 'see', 'walk'],
    correct_index: 0,
    explanation_jp: '「enjoy 〜ing」で「〜することを楽しむ」です。週末を楽しむという意味になります。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-enjoy', 'gerund'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-002 動詞 visit
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'We will (   ) our grandmother next Sunday.',
    choices: ['visit', 'eat', 'wash', 'open'],
    correct_index: 0,
    explanation_jp: '「visit」は「訪問する」「会いに行く」という意味です。おばあさんに会いに行くという文脈です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-visit', 'family'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-003 動詞 help
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I always (   ) my mother in the kitchen.',
    choices: ['help', 'sing', 'jump', 'run'],
    correct_index: 0,
    explanation_jp: '「help」は「手伝う」という意味です。お母さんを台所で手伝うという文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-help', 'family'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-004 動詞 wait
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'Please (   ) for me at the gate.',
    choices: ['wait', 'eat', 'sing', 'jump'],
    correct_index: 0,
    explanation_jp: '「wait for 〜」で「〜を待つ」という意味です。門で待っていてください、という文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-wait', 'school-life'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-005 動詞 buy
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I want to (   ) a new game.',
    choices: ['buy', 'sing', 'walk', 'jump'],
    correct_index: 0,
    explanation_jp: '「buy」は「買う」という意味です。新しいゲームを買いたい、という文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-buy', 'shopping'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-006 動詞 sell
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'The shop (   ) fresh fruit every day.',
    choices: ['sells', 'eats', 'sings', 'jumps'],
    correct_index: 0,
    explanation_jp: '「sell」は「売る」という意味です。お店が果物を売る、という文です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['verb-sell', 'shopping'],
    copyright_safe: true,
    generated_quality_score: 0.89,
  },
  // V4-007 動詞 teach
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'Ms. Brown (   ) us English at Sakura Elementary.',
    choices: ['teaches', 'eats', 'opens', 'visits'],
    correct_index: 0,
    explanation_jp: '「teach」は「教える」という意味です。先生が英語を教える、という文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-teach', 'school'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-008 動詞 learn
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I (   ) new English words every day.',
    choices: ['learn', 'eat', 'jump', 'sing'],
    correct_index: 0,
    explanation_jp: '「learn」は「学ぶ」という意味です。毎日新しい単語を学ぶ、という文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-learn', 'school'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-009 動詞 wash
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I (   ) my hands before lunch.',
    choices: ['wash', 'eat', 'walk', 'sing'],
    correct_index: 0,
    explanation_jp: '「wash」は「洗う」という意味です。昼ごはん前に手を洗う、という文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-wash', 'daily'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-010 動詞 cook
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'My father can (   ) Japanese food well.',
    choices: ['cook', 'sing', 'jump', 'walk'],
    correct_index: 0,
    explanation_jp: '「cook」は「料理する」という意味です。父が日本料理を上手に作るという文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-cook', 'family'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-011 動詞 clean
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'We (   ) our classroom every Friday.',
    choices: ['clean', 'eat', 'sing', 'walk'],
    correct_index: 0,
    explanation_jp: '「clean」は「そうじする」という意味です。教室をそうじするという文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-clean', 'school-life'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-012 動詞 use
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'May I (   ) your eraser?',
    choices: ['use', 'eat', 'walk', 'sing'],
    correct_index: 0,
    explanation_jp: '「use」は「使う」という意味です。消しゴムを使ってもいいですか、という文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-use', 'classroom'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-013 動詞 make
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I will (   ) a card for my mother.',
    choices: ['make', 'eat', 'walk', 'sleep'],
    correct_index: 0,
    explanation_jp: '「make」は「作る」という意味です。母にカードを作るという文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-make', 'family'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-014 動詞 give
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I will (   ) this book to my sister.',
    choices: ['give', 'eat', 'walk', 'jump'],
    correct_index: 0,
    explanation_jp: '「give」は「あげる」という意味です。妹に本をあげるという文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-give', 'family'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-015 動詞 take
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I (   ) the bus to school.',
    choices: ['take', 'eat', 'walk', 'sing'],
    correct_index: 0,
    explanation_jp: '「take」は「（乗り物に）乗る」という意味です。バスに乗って学校に行くという文です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['verb-take', 'transport'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V4-016 動詞 send
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I will (   ) you a letter from Hanei Town.',
    choices: ['send', 'eat', 'walk', 'sing'],
    correct_index: 0,
    explanation_jp: '「send」は「送る」という意味です。手紙を送る、という文です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['verb-send', 'communication'],
    copyright_safe: true,
    generated_quality_score: 0.89,
  },
  // V4-017 動詞 bring
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'Please (   ) your textbook to class tomorrow.',
    choices: ['bring', 'eat', 'walk', 'sing'],
    correct_index: 0,
    explanation_jp: '「bring」は「持ってくる」という意味です。教科書を授業に持ってきてください、という文です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['verb-bring', 'school'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V4-018 動詞 know
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'Do you (   ) Mike\'s phone number?',
    choices: ['know', 'eat', 'walk', 'sing'],
    correct_index: 0,
    explanation_jp: '「know」は「知っている」という意味です。電話番号を知っているか聞く文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-know'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-019 動詞 think
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I (   ) this book is very interesting.',
    choices: ['think', 'eat', 'walk', 'sing'],
    correct_index: 0,
    explanation_jp: '「think」は「思う」「考える」という意味です。本がおもしろいと思う、という文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-think'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-020 動詞 understand
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I cannot (   ) this English sentence.',
    choices: ['understand', 'eat', 'walk', 'sing'],
    correct_index: 0,
    explanation_jp: '「understand」は「理解する」という意味です。文を理解できないという文です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['verb-understand'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V4-021 名詞 学校 - classroom
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'Our (   ) is on the second floor.',
    choices: ['classroom', 'apple', 'milk', 'shoe'],
    correct_index: 0,
    explanation_jp: '「classroom」は「教室」という意味です。2 階にあるのは教室として自然です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-school', 'classroom'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-022 名詞 学校 - library
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I read books in the (   ) after school.',
    choices: ['library', 'kitchen', 'park', 'shoe'],
    correct_index: 0,
    explanation_jp: '「library」は「図書館」「図書室」という意味です。本を読む場所として最も自然です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-school', 'library'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-023 名詞 学校 - homework
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I do my (   ) every evening.',
    choices: ['homework', 'shoe', 'apple', 'water'],
    correct_index: 0,
    explanation_jp: '「homework」は「宿題」という意味です。毎晩する活動として宿題が自然です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-school', 'homework'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-024 名詞 学校 - subject
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'My favorite (   ) is math.',
    choices: ['subject', 'apple', 'shoe', 'water'],
    correct_index: 0,
    explanation_jp: '「subject」は「教科」という意味です。math（算数）は教科の例です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['noun-school', 'subject'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V4-025 名詞 学校 - lunch
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'We have (   ) at noon at school.',
    choices: ['lunch', 'shoe', 'apple', 'window'],
    correct_index: 0,
    explanation_jp: '「lunch」は「昼食」という意味です。お昼の12時に食べる食事です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-meal', 'lunch'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-026 名詞 学校 - club
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I am in the soccer (   ) at school.',
    choices: ['club', 'apple', 'milk', 'shoe'],
    correct_index: 0,
    explanation_jp: '「club」は「クラブ」「部活」という意味です。学校のサッカー部、という文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-school', 'club'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-027 名詞 学校 - test
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'We have a math (   ) tomorrow.',
    choices: ['test', 'apple', 'shoe', 'water'],
    correct_index: 0,
    explanation_jp: '「test」は「テスト」という意味です。明日のテストがあるという文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-school', 'test'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-028 名詞 学校 - desk
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'My books are on the (   ) in my room.',
    choices: ['desk', 'apple', 'shoe', 'water'],
    correct_index: 0,
    explanation_jp: '「desk」は「机」という意味です。本をのせる場所として机が自然です。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['noun-furniture', 'desk'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-029 名詞 family - grandfather
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'My (   ) lives in Hanei Town. He is 75 years old.',
    choices: ['grandfather', 'classroom', 'lunch', 'pencil'],
    correct_index: 0,
    explanation_jp: '「grandfather」は「おじいさん」という意味です。75歳という年齢からも自然です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-family', 'grandfather'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-030 名詞 family - grandmother
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'My (   ) makes good cookies. I love her cookies.',
    choices: ['grandmother', 'classroom', 'lunch', 'pencil'],
    correct_index: 0,
    explanation_jp: '「grandmother」は「おばあさん」という意味です。「her」とあるので女の人です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-family', 'grandmother'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-031 名詞 family - parents
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'My (   ) take me to the park on weekends.',
    choices: ['parents', 'pencils', 'apples', 'shoes'],
    correct_index: 0,
    explanation_jp: '「parents」は「両親」という意味です。父と母をまとめて言う言葉です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['noun-family', 'parents'],
    copyright_safe: true,
    generated_quality_score: 0.89,
  },
  // V4-032 名詞 family - aunt
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'My (   ) is my mother\'s sister.',
    choices: ['aunt', 'apple', 'shoe', 'window'],
    correct_index: 0,
    explanation_jp: '「aunt」は「おば」という意味です。お母さんの姉や妹を表します。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['noun-family', 'aunt'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V4-033 名詞 family - uncle
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'My (   ) is my father\'s brother.',
    choices: ['uncle', 'apple', 'shoe', 'window'],
    correct_index: 0,
    explanation_jp: '「uncle」は「おじ」という意味です。お父さんの兄や弟を表します。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['noun-family', 'uncle'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V4-034 名詞 family - cousin
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'My (   ) is the same age as me. We play together.',
    choices: ['cousin', 'pencil', 'shoe', 'window'],
    correct_index: 0,
    explanation_jp: '「cousin」は「いとこ」という意味です。同じ年でいっしょに遊ぶ家族関係です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['noun-family', 'cousin'],
    copyright_safe: true,
    generated_quality_score: 0.87,
  },
  // V4-035 食べ物 - vegetable
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I eat many (   ) like carrots and tomatoes.',
    choices: ['vegetables', 'pencils', 'shoes', 'desks'],
    correct_index: 0,
    explanation_jp: '「vegetables」は「野菜」という意味です。ニンジンやトマトは野菜の例です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-food', 'vegetable'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-036 食べ物 - fruit
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'Apples and bananas are (   ).',
    choices: ['fruit', 'pencils', 'shoes', 'desks'],
    correct_index: 0,
    explanation_jp: '「fruit」は「果物」という意味です。リンゴやバナナは果物の例です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-food', 'fruit'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-037 食べ物 - dinner
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'We eat (   ) at seven in the evening.',
    choices: ['dinner', 'pencils', 'shoes', 'desks'],
    correct_index: 0,
    explanation_jp: '「dinner」は「夕食」という意味です。夕方の7時に食べる食事です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-meal', 'dinner'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-038 食べ物 - water
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I am thirsty. Please give me some (   ).',
    choices: ['water', 'pencils', 'shoes', 'desks'],
    correct_index: 0,
    explanation_jp: '「water」は「水」という意味です。のどがかわいたときに飲むものです。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['noun-drink', 'water'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V4-039 食べ物 - cake
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'My mother makes a (   ) on my birthday.',
    choices: ['cake', 'shoe', 'desk', 'window'],
    correct_index: 0,
    explanation_jp: '「cake」は「ケーキ」という意味です。誕生日に作る定番のものです。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['noun-food', 'cake'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V4-040 食べ物 - egg
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I eat an (   ) for breakfast.',
    choices: ['egg', 'shoe', 'desk', 'window'],
    correct_index: 0,
    explanation_jp: '「egg」は「卵」という意味です。朝食によく食べる食材です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['noun-food', 'egg'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // V4-041 名詞 - friend
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'Lily is my best (   ). We always play together.',
    choices: ['friend', 'shoe', 'desk', 'window'],
    correct_index: 0,
    explanation_jp: '「friend」は「友達」という意味です。いつもいっしょに遊ぶ人を表します。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['noun-people', 'friend'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // V4-042 形容詞 interesting
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'This book is very (   ). I cannot stop reading.',
    choices: ['interesting', 'short', 'cold', 'hungry'],
    correct_index: 0,
    explanation_jp: '「interesting」は「おもしろい」という意味です。読むのがやめられない本のようすを表します。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['adjective-emotion', 'interesting'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V4-043 形容詞 difficult
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'This math problem is too (   ) for me.',
    choices: ['difficult', 'happy', 'hungry', 'cold'],
    correct_index: 0,
    explanation_jp: '「difficult」は「むずかしい」という意味です。算数の問題がむずかしすぎる、という文です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['adjective', 'difficult'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V4-044 形容詞 easy
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'This question is (   ). I can answer it.',
    choices: ['easy', 'hungry', 'cold', 'tall'],
    correct_index: 0,
    explanation_jp: '「easy」は「かんたん」という意味です。答えられるのでかんたんな問題です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['adjective', 'easy'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-045 形容詞 busy
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'My father is (   ) this week. He works late.',
    choices: ['busy', 'hungry', 'cold', 'short'],
    correct_index: 0,
    explanation_jp: '「busy」は「いそがしい」という意味です。おそくまで仕事をするのでいそがしいです。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['adjective', 'busy'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V4-046 形容詞 hungry
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I am (   ). Let\'s have lunch.',
    choices: ['hungry', 'busy', 'cold', 'short'],
    correct_index: 0,
    explanation_jp: '「hungry」は「おなかがすいた」という意味です。お昼を食べようと言っているので空腹です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['adjective-feeling', 'hungry'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V4-047 形容詞 tired
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I am (   ) after the soccer game.',
    choices: ['tired', 'hungry', 'cold', 'tall'],
    correct_index: 0,
    explanation_jp: '「tired」は「つかれた」という意味です。試合のあとはつかれます。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['adjective-feeling', 'tired'],
    copyright_safe: true,
    generated_quality_score: 0.89,
  },
  // V4-048 副詞 always
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'Mike (   ) walks to school. He never takes the bus.',
    choices: ['always', 'never', 'sometimes', 'today'],
    correct_index: 0,
    explanation_jp: '「always」は「いつも」という意味です。「never takes the bus（バスに乗らない）」と対になり、「いつも歩く」が自然です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['adverb-frequency', 'always'],
    copyright_safe: true,
    generated_quality_score: 0.87,
  },
  // V4-049 副詞 sometimes
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I (   ) play tennis on Saturdays.',
    choices: ['sometimes', 'never', 'today', 'now'],
    correct_index: 0,
    explanation_jp: '「sometimes」は「ときどき」という意味です。土曜日にときどきテニスをする、という文です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['adverb-frequency', 'sometimes'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V4-050 動詞 want to
  {
    level: 'eiken-4',
    skill: 'vocab',
    prompt_text: 'I (   ) to be a teacher in the future.',
    choices: ['want', 'eat', 'walk', 'sing'],
    correct_index: 0,
    explanation_jp: '「want to + 動詞の原形」で「〜したい」です。先生になりたい、という文です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['verb-want', 'infinitive'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },

  // ============================================================
  // 4級 listening-response 20 問（L4-001 〜 L4-020）
  // 範囲: 短い英会話 1 往復 → 応答選択
  // 形式: A の発言 → B が選ぶ最適応答（4択）
  // 各問題に audio_transcript（A の発言）を付与
  // ============================================================

  // L4-001 あいさつ
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: How are you today?',
    choices: ["I'm fine, thank you.", 'It is a desk.', 'I have a cat.', 'Yes, I do.'],
    correct_index: 0,
    explanation_jp: '「How are you?」は「元気ですか」という意味です。「I\'m fine, thank you.」（元気です、ありがとう）が自然な答えです。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['listening', 'greeting'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // L4-002 名前を聞く
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: What is your name?',
    choices: ['My name is Lily.', 'It is a pen.', "I'm fine.", 'Yes, I do.'],
    correct_index: 0,
    explanation_jp: '「What is your name?」は名前を聞く質問です。「My name is 〜」と名前を答えます。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['listening', 'name'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // L4-003 場所を聞く
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: Where is your bag?',
    choices: ['It is on my desk.', 'I am fine.', 'My name is Tom.', 'Yes, please.'],
    correct_index: 0,
    explanation_jp: '「Where」は場所を聞く質問です。「on my desk」と場所を答えています。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['listening', 'where'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // L4-004 時刻を聞く
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: What time is it now?',
    choices: ['It is three o\'clock.', 'I have a cat.', 'Yes, I am.', 'On the desk.'],
    correct_index: 0,
    explanation_jp: '「What time is it?」は時刻を聞く質問です。「three o\'clock」と時刻を答えます。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['listening', 'time'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // L4-005 食べ物を聞く
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: What food do you like?',
    choices: ['I like pizza.', 'It is in the bag.', 'I am happy.', 'Yes, please.'],
    correct_index: 0,
    explanation_jp: '「What food do you like?」は好きな食べ物を聞く質問です。具体的な食べ物名で答えます。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['listening', 'food'],
    copyright_safe: true,
    generated_quality_score: 0.92,
  },
  // L4-006 yes/no 質問
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: Do you like dogs?',
    choices: ['Yes, I do.', 'It is a cat.', 'My name is Ben.', 'In the park.'],
    correct_index: 0,
    explanation_jp: '「Do you 〜?」の質問には「Yes, I do.」または「No, I don\'t.」で答えます。',
    difficulty: 0,
    estimated_time_sec: 25,
    tags: ['listening', 'yes-no'],
    copyright_safe: true,
    generated_quality_score: 0.93,
  },
  // L4-007 yes/no 質問 are you
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: Are you a student?',
    choices: ['Yes, I am.', 'Yes, I do.', 'It is a book.', 'In the kitchen.'],
    correct_index: 0,
    explanation_jp: 'be 動詞「Are you 〜?」の質問は「Yes, I am.」または「No, I am not.」で答えます。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['listening', 'be-verb-question'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // L4-008 趣味を聞く
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: What sport do you play?',
    choices: ['I play tennis.', 'It is fine.', 'In my room.', 'Yes, please.'],
    correct_index: 0,
    explanation_jp: '「What sport do you play?」はするスポーツを聞いています。具体的なスポーツ名で答えます。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['listening', 'sport'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // L4-009 数を聞く
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: How many books do you have?',
    choices: ['I have ten books.', 'It is a pen.', 'In the bag.', 'Yes, I do.'],
    correct_index: 0,
    explanation_jp: '「How many 〜?」は数を聞く質問です。具体的な数で答えます。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['listening', 'how-many'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // L4-010 提案
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a suggestion. Choose the best response.',
    audio_transcript: "A: Let's play soccer after school.",
    choices: ['That sounds good.', 'It is a desk.', 'I have a dog.', 'In my room.'],
    correct_index: 0,
    explanation_jp: '「Let\'s 〜」（〜しよう）の提案には「That sounds good.」（いいね）と答えます。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['listening', 'lets', 'agreement'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // L4-011 お願い
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: Can you help me, please?',
    choices: ['Sure, no problem.', 'It is on the desk.', 'My name is Mike.', 'Yes, I am.'],
    correct_index: 0,
    explanation_jp: '「Can you 〜?」のお願いには「Sure, no problem.」（もちろんいいよ）と答えます。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['listening', 'request'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // L4-012 出身を聞く
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: Where are you from?',
    choices: ["I'm from Hanei Town.", 'It is a cat.', 'Yes, I do.', 'In my bag.'],
    correct_index: 0,
    explanation_jp: '「Where are you from?」は出身を聞く質問です。「I\'m from 〜」で答えます。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['listening', 'origin'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // L4-013 趣味
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: What do you like to do?',
    choices: ['I like to read books.', 'It is a desk.', 'In the kitchen.', "Yes, I'm fine."],
    correct_index: 0,
    explanation_jp: '「What do you like to do?」は好きなことを聞く質問です。「I like to 〜」で答えます。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['listening', 'hobby'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // L4-014 誕生日
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: When is your birthday?',
    choices: ['It is in April.', 'I have a cat.', 'On the desk.', 'My name is Tom.'],
    correct_index: 0,
    explanation_jp: '「When is your birthday?」は誕生日を聞く質問です。月で答えるのが自然です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['listening', 'birthday'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // L4-015 天気
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: "A: How's the weather today?",
    choices: ["It's sunny.", 'My name is Lily.', 'In my room.', 'Yes, I do.'],
    correct_index: 0,
    explanation_jp: '「How\'s the weather?」は天気を聞く質問です。「sunny」（晴れ）など天気を答えます。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['listening', 'weather'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // L4-016 電話
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: May I speak to Lily, please?',
    choices: ['Just a moment, please.', 'It is a book.', 'In the park.', 'My name is Tom.'],
    correct_index: 0,
    explanation_jp: '電話で「〜とお話しできますか」と聞かれたら「ちょっと待ってね」と返すのが自然です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['listening', 'phone'],
    copyright_safe: true,
    generated_quality_score: 0.87,
  },
  // L4-017 行き先
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: "A: Where are you going?",
    choices: ["I'm going to the library.", 'I have a dog.', "It's three o'clock.", 'Yes, I am.'],
    correct_index: 0,
    explanation_jp: '「Where are you going?」は行き先を聞く質問です。「I\'m going to 〜」で答えます。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['listening', 'going'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // L4-018 食事の誘い
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a suggestion. Choose the best response.',
    audio_transcript: 'A: Would you like some tea?',
    choices: ['Yes, please.', 'It is on the desk.', 'My name is Mike.', 'In my room.'],
    correct_index: 0,
    explanation_jp: '「Would you like 〜?」（〜はいかが？）の質問には「Yes, please.」と答えます。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['listening', 'offer'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // L4-019 値段
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a question. Choose the best response.',
    audio_transcript: 'A: How much is this book?',
    choices: ['It is five dollars.', 'I have a cat.', 'Yes, I do.', 'In the park.'],
    correct_index: 0,
    explanation_jp: '「How much 〜?」は値段を聞く質問です。「five dollars」とお金で答えます。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['listening', 'price'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // L4-020 体調
  {
    level: 'eiken-4',
    skill: 'listening-response',
    prompt_text: 'You will hear a comment. Choose the best response.',
    audio_transcript: "A: I'm so tired today.",
    choices: ['Take a rest.', 'It is a desk.', 'In the kitchen.', 'My name is Ben.'],
    correct_index: 0,
    explanation_jp: '「つかれた」と言う相手には「Take a rest.」（休んでね）と返すのが自然です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['listening', 'feeling'],
    copyright_safe: true,
    generated_quality_score: 0.87,
  },

  // ============================================================
  // 3級 vocab 30 問（V3-001 〜 V3-030）
  // 範囲: 過去形 / 受動態 / 基本句動詞
  // ============================================================

  // V3-001 過去形 went
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I (   ) to the library yesterday.',
    choices: ['went', 'go', 'goes', 'going'],
    correct_index: 0,
    explanation_jp: '「yesterday」（きのう）があるので過去形を使います。go の過去形は「went」です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['past-tense', 'go-went'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V3-002 過去形 ate
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'We (   ) sushi for dinner last night.',
    choices: ['ate', 'eat', 'eats', 'eating'],
    correct_index: 0,
    explanation_jp: '「last night」（昨夜）があるので過去形を使います。eat の過去形は「ate」です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['past-tense', 'eat-ate'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V3-003 過去形 saw
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I (   ) a beautiful bird in the park last week.',
    choices: ['saw', 'see', 'sees', 'seeing'],
    correct_index: 0,
    explanation_jp: '「last week」があるので過去形を使います。see の過去形は「saw」です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['past-tense', 'see-saw'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V3-004 過去形 made
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'She (   ) a cake for her brother yesterday.',
    choices: ['made', 'make', 'makes', 'making'],
    correct_index: 0,
    explanation_jp: '「yesterday」があるので過去形を使います。make の過去形は「made」です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['past-tense', 'make-made'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V3-005 過去形 took
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I (   ) some pictures at the festival last summer.',
    choices: ['took', 'take', 'takes', 'taking'],
    correct_index: 0,
    explanation_jp: '「last summer」があるので過去形を使います。take の過去形は「took」です。「take pictures」で写真を撮るという意味です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['past-tense', 'take-took'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V3-006 過去形 gave
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'My uncle (   ) me a present for my birthday.',
    choices: ['gave', 'give', 'gives', 'giving'],
    correct_index: 0,
    explanation_jp: '誕生日プレゼントを受け取った文脈は過去形です。give の過去形は「gave」です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['past-tense', 'give-gave'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // V3-007 過去形 wrote
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I (   ) a letter to my grandmother last weekend.',
    choices: ['wrote', 'write', 'writes', 'writing'],
    correct_index: 0,
    explanation_jp: '「last weekend」があるので過去形です。write の過去形は「wrote」です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['past-tense', 'write-wrote'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V3-008 過去形 read
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I (   ) an interesting book yesterday.',
    choices: ['read', 'reads', 'reading', 'to read'],
    correct_index: 0,
    explanation_jp: 'read の過去形はつづりは同じ「read」ですが、発音は「レッド」になります。「yesterday」があるので過去形です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['past-tense', 'read'],
    copyright_safe: true,
    generated_quality_score: 0.86,
  },
  // V3-009 受動態 is loved
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'This song (   ) by many people in Hanei Town.',
    choices: ['is loved', 'loves', 'loving', 'love'],
    correct_index: 0,
    explanation_jp: '「〜される」という受動態は「be 動詞 + 過去分詞」で表します。「is loved」（愛されている）が正解です。',
    difficulty: 2,
    estimated_time_sec: 40,
    tags: ['passive', 'is-loved'],
    copyright_safe: true,
    generated_quality_score: 0.86,
  },
  // V3-010 受動態 was made
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'This bread (   ) by my mother this morning.',
    choices: ['was made', 'makes', 'making', 'make'],
    correct_index: 0,
    explanation_jp: '「〜された」という過去の受動態は「was/were + 過去分詞」です。make の過去分詞は「made」です。',
    difficulty: 2,
    estimated_time_sec: 40,
    tags: ['passive-past', 'was-made'],
    copyright_safe: true,
    generated_quality_score: 0.86,
  },
  // V3-011 受動態 is spoken
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'English (   ) in many countries.',
    choices: ['is spoken', 'speaks', 'speaking', 'speak'],
    correct_index: 0,
    explanation_jp: '「英語が話されている」という意味の受動態です。speak の過去分詞は「spoken」です。',
    difficulty: 2,
    estimated_time_sec: 40,
    tags: ['passive', 'is-spoken'],
    copyright_safe: true,
    generated_quality_score: 0.85,
  },
  // V3-012 受動態 was written
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'This book (   ) a long time ago.',
    choices: ['was written', 'writes', 'writing', 'write'],
    correct_index: 0,
    explanation_jp: '「ずっと昔に書かれた」という過去の受動態です。write の過去分詞は「written」です。',
    difficulty: 2,
    estimated_time_sec: 40,
    tags: ['passive-past', 'was-written'],
    copyright_safe: true,
    generated_quality_score: 0.84,
  },
  // V3-013 句動詞 look for
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: "I'm looking (   ) my pen. Have you seen it?",
    choices: ['for', 'at', 'in', 'on'],
    correct_index: 0,
    explanation_jp: '「look for 〜」で「〜を探す」という意味です。なくしたペンを探しています。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['phrasal-verb', 'look-for'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V3-014 句動詞 look at
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'Please look (   ) this picture. It is so beautiful.',
    choices: ['at', 'for', 'in', 'over'],
    correct_index: 0,
    explanation_jp: '「look at 〜」で「〜を見る」という意味です。何かに目を向けるときに使います。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['phrasal-verb', 'look-at'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // V3-015 句動詞 listen to
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I listen (   ) music every night.',
    choices: ['to', 'at', 'on', 'in'],
    correct_index: 0,
    explanation_jp: '「listen to 〜」で「〜を聞く」という意味です。「listen」のあとは必ず「to」を続けます。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['phrasal-verb', 'listen-to'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V3-016 句動詞 wait for
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: "I'm waiting (   ) the bus at the bus stop.",
    choices: ['for', 'at', 'on', 'to'],
    correct_index: 0,
    explanation_jp: '「wait for 〜」で「〜を待つ」という意味です。バスを待っています。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['phrasal-verb', 'wait-for'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V3-017 句動詞 get up
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I (   ) at six every morning.',
    choices: ['get up', 'go up', 'put up', 'take up'],
    correct_index: 0,
    explanation_jp: '「get up」で「起きる」という意味です。朝の起床を表します。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['phrasal-verb', 'get-up'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V3-018 句動詞 go to bed
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I (   ) at ten every night.',
    choices: ['go to bed', 'go to school', 'go to park', 'go to lunch'],
    correct_index: 0,
    explanation_jp: '「go to bed」で「ねる」という意味です。夜の就寝を表します。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['phrasal-verb', 'go-to-bed'],
    copyright_safe: true,
    generated_quality_score: 0.91,
  },
  // V3-019 動詞 過去形 had
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'We (   ) a great time at the park last Sunday.',
    choices: ['had', 'have', 'has', 'having'],
    correct_index: 0,
    explanation_jp: 'have の過去形は「had」です。「had a great time」で「楽しい時間を過ごした」という意味です。',
    difficulty: 1,
    estimated_time_sec: 30,
    tags: ['past-tense', 'have-had'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // V3-020 過去形 came
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'My cousin (   ) to my house last weekend.',
    choices: ['came', 'come', 'comes', 'coming'],
    correct_index: 0,
    explanation_jp: 'come の過去形は「came」です。「last weekend」があるので過去形を使います。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['past-tense', 'come-came'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V3-021 過去形 bought
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I (   ) a new bag at the shop yesterday.',
    choices: ['bought', 'buy', 'buys', 'buying'],
    correct_index: 0,
    explanation_jp: 'buy の過去形は「bought」です。読み方は「ボート」です。「yesterday」があるので過去形を使います。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['past-tense', 'buy-bought'],
    copyright_safe: true,
    generated_quality_score: 0.86,
  },
  // V3-022 過去形 found
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I (   ) my lost key under the desk.',
    choices: ['found', 'find', 'finds', 'finding'],
    correct_index: 0,
    explanation_jp: 'find の過去形は「found」です。なくした鍵を見つけたという文です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['past-tense', 'find-found'],
    copyright_safe: true,
    generated_quality_score: 0.86,
  },
  // V3-023 句動詞 turn on
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'It is dark in the room. Please (   ) the light.',
    choices: ['turn on', 'turn off', 'turn at', 'turn in'],
    correct_index: 0,
    explanation_jp: '「turn on」で「（明かり・テレビなどを）つける」です。暗いので明かりをつけます。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['phrasal-verb', 'turn-on'],
    copyright_safe: true,
    generated_quality_score: 0.87,
  },
  // V3-024 句動詞 turn off
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: "I'm going to bed. Please (   ) the TV.",
    choices: ['turn off', 'turn on', 'turn at', 'turn out'],
    correct_index: 0,
    explanation_jp: '「turn off」で「（明かり・テレビなどを）消す」です。寝るので消します。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['phrasal-verb', 'turn-off'],
    copyright_safe: true,
    generated_quality_score: 0.87,
  },
  // V3-025 動詞 understand 過去形
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I (   ) the question after the teacher explained it again.',
    choices: ['understood', 'understand', 'understands', 'understanding'],
    correct_index: 0,
    explanation_jp: 'understand の過去形は「understood」です。説明を聞いて理解したという過去の出来事です。',
    difficulty: 2,
    estimated_time_sec: 40,
    tags: ['past-tense', 'understand-understood'],
    copyright_safe: true,
    generated_quality_score: 0.85,
  },
  // V3-026 動詞 swam
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'I (   ) in the pool last summer.',
    choices: ['swam', 'swim', 'swims', 'swimming'],
    correct_index: 0,
    explanation_jp: 'swim の過去形は「swam」です。「last summer」があるので過去形を使います。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['past-tense', 'swim-swam'],
    copyright_safe: true,
    generated_quality_score: 0.86,
  },
  // V3-027 名詞 future
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'In the (   ), I want to be a doctor.',
    choices: ['future', 'past', 'morning', 'kitchen'],
    correct_index: 0,
    explanation_jp: '「future」は「未来」「将来」という意味です。「in the future」で「将来」という決まった言い方です。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['noun', 'future'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // V3-028 動詞 become 過去形
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'My sister (   ) a teacher last year.',
    choices: ['became', 'become', 'becomes', 'becoming'],
    correct_index: 0,
    explanation_jp: 'become の過去形は「became」です。「last year」があるので過去形を使います。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['past-tense', 'become-became'],
    copyright_safe: true,
    generated_quality_score: 0.86,
  },
  // V3-029 接続詞 because
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: "I am tired (   ) I studied for many hours.",
    choices: ['because', 'but', 'or', 'so'],
    correct_index: 0,
    explanation_jp: '「because」は「〜だから」「〜なので」という意味です。理由を表します。',
    difficulty: 2,
    estimated_time_sec: 35,
    tags: ['conjunction', 'because'],
    copyright_safe: true,
    generated_quality_score: 0.87,
  },
  // V3-030 動詞 grow up
  {
    level: 'eiken-3',
    skill: 'vocab',
    prompt_text: 'My brother wants to (   ) and become a soccer player.',
    choices: ['grow up', 'sit down', 'stand up', 'wake up'],
    correct_index: 0,
    explanation_jp: '「grow up」で「大きくなる」「成長する」です。将来サッカー選手になりたい、という文脈に合います。',
    difficulty: 2,
    estimated_time_sec: 40,
    tags: ['phrasal-verb', 'grow-up'],
    copyright_safe: true,
    generated_quality_score: 0.85,
  },

  // ============================================================
  // 3級 reading 10 問（R3-001 〜 R3-010）
  // 形式: 80-120 語の本文 + 設問 1 問（4 択）
  // 1 設問 = 1 Problem として登録
  // 子どもの日常（学校・家族・週末・趣味・季節）が題材
  // ============================================================

  // R3-001 学校生活
  {
    level: 'eiken-3',
    skill: 'reading',
    prompt_text: 'What does Lily do after school on Mondays?',
    passage_text:
      'Lily is a fifth grade student at Sakura Elementary in Hanei Town. She has many things to do every week. On Mondays, she goes to the library and reads books for one hour. On Wednesdays, she plays the piano with her teacher. On Fridays, she practices tennis with her friends in the park. On weekends, Lily helps her mother clean the house. She also writes a short letter to her grandmother every Sunday. Lily is busy, but she enjoys her days very much.',
    choices: [
      'She reads books in the library.',
      'She plays the piano.',
      'She practices tennis.',
      'She writes a letter.',
    ],
    correct_index: 0,
    explanation_jp: '本文に「On Mondays, she goes to the library and reads books」と書かれています。月曜日は図書館で本を読みます。',
    difficulty: 1,
    estimated_time_sec: 90,
    tags: ['reading', 'school-life', 'detail'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // R3-002 家族
  {
    level: 'eiken-3',
    skill: 'reading',
    prompt_text: 'Who cooks dinner in Tom\'s family?',
    passage_text:
      'Tom lives with his family in Hanei Town. His family has four members: his father, his mother, his sister Mary, and Tom. His father works at a hospital and comes home late. His mother is a teacher at Sakura Elementary, but she always cooks dinner for the family. Mary is in junior high school and likes to help her mother in the kitchen. Tom\'s job is to wash the dishes after dinner. Every Sunday, the family eats lunch together at a restaurant near the park.',
    choices: [
      'His mother does.',
      'His father does.',
      'His sister Mary does.',
      'Tom does.',
    ],
    correct_index: 0,
    explanation_jp: '本文に「his mother ... always cooks dinner for the family」とあります。お母さんが夕食を作ります。',
    difficulty: 1,
    estimated_time_sec: 90,
    tags: ['reading', 'family', 'detail'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // R3-003 趣味
  {
    level: 'eiken-3',
    skill: 'reading',
    prompt_text: 'When did Ben start to learn the guitar?',
    passage_text:
      'Ben is a sixth grade student. He likes music very much. Last year, his uncle gave him a guitar for his birthday. From that day, Ben started to learn the guitar from his uncle every weekend. At first, it was very difficult. But Ben practiced for thirty minutes every day. Now, he can play three songs. Next month, Ben will play the guitar at the school festival. His family and friends will come to listen. Ben is a little nervous, but he is also very excited.',
    choices: [
      'Last year, on his birthday.',
      'When he was in the fifth grade.',
      'After the school festival.',
      'Three months ago.',
    ],
    correct_index: 0,
    explanation_jp: '本文に「Last year, his uncle gave him a guitar for his birthday. From that day, Ben started to learn the guitar」とあります。去年の誕生日が始まりです。',
    difficulty: 2,
    estimated_time_sec: 100,
    tags: ['reading', 'hobby', 'time-detail'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // R3-004 週末
  {
    level: 'eiken-3',
    skill: 'reading',
    prompt_text: 'What did Mary do on Saturday afternoon?',
    passage_text:
      'Last weekend, Mary had a very good time. On Saturday morning, she got up at seven and helped her mother make breakfast. They cooked eggs and toast together. After breakfast, Mary went to the park with her father. They played catch for one hour. In the afternoon, Mary visited her grandmother and read a book to her. Her grandmother was very happy. On Sunday, Mary did her homework in the morning, and then watched a movie with her brother in the evening. Mary loves her weekends with her family.',
    choices: [
      'She visited her grandmother.',
      'She made breakfast.',
      'She played catch in the park.',
      'She watched a movie.',
    ],
    correct_index: 0,
    explanation_jp: '本文に「In the afternoon, Mary visited her grandmother」とあります。土曜日の午後はおばあさんを訪ねました。',
    difficulty: 2,
    estimated_time_sec: 100,
    tags: ['reading', 'weekend', 'time-detail'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // R3-005 季節 / 体験
  {
    level: 'eiken-3',
    skill: 'reading',
    prompt_text: 'Why was Ken excited last summer?',
    passage_text:
      'Last summer, Ken went to the beach with his family. It was his first time to see the sea. The water was very blue and the sand was warm. Ken was so excited. He swam with his father for a long time. His mother and sister built a big sand castle. They had lunch on the beach: rice balls and cold tea. In the evening, they watched the sunset together. Ken took many pictures with his camera. He wants to go to the beach again next summer.',
    choices: [
      'It was his first time to see the sea.',
      'He met his cousin at the beach.',
      'He found a new shell.',
      'He played soccer with his father.',
    ],
    correct_index: 0,
    explanation_jp: '本文に「It was his first time to see the sea ... Ken was so excited」とあります。海を初めて見たから興奮していました。',
    difficulty: 2,
    estimated_time_sec: 100,
    tags: ['reading', 'season', 'reason'],
    copyright_safe: true,
    generated_quality_score: 0.87,
  },
  // R3-006 学校行事
  {
    level: 'eiken-3',
    skill: 'reading',
    prompt_text: 'What time will the school festival start?',
    passage_text:
      'Sakura Elementary will have a school festival next Saturday. The festival will start at ten in the morning and finish at three in the afternoon. Students from each class will sell food and play games. Lily\'s class will sell hot dogs and juice. Tom\'s class will run a small game corner. Many parents and friends will come. Last year, more than two hundred people visited the festival. The teachers say that this year will be even more fun. Lily and Tom are very busy because they are getting ready for the big day.',
    choices: [
      'At ten in the morning.',
      'At nine in the morning.',
      'At three in the afternoon.',
      'At noon.',
    ],
    correct_index: 0,
    explanation_jp: '本文に「The festival will start at ten in the morning」とあります。朝の10時に始まります。',
    difficulty: 1,
    estimated_time_sec: 90,
    tags: ['reading', 'event', 'time-detail'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // R3-007 動物 / ペット
  {
    level: 'eiken-3',
    skill: 'reading',
    prompt_text: 'What does Mike\'s dog like to do?',
    passage_text:
      'Mike has a dog. Its name is Coco. Coco is two years old and very small. She has soft brown hair. Mike got Coco when he was nine. Coco likes to play in the park near Mike\'s house. Every morning, Mike walks with her for thirty minutes. Coco runs after balls and jumps in the grass. She is also very kind to Mike\'s little sister. Sometimes Coco sleeps on the sofa next to her. Mike thinks Coco is the best dog in the world.',
    choices: [
      'She likes to play in the park.',
      'She likes to swim in the river.',
      'She likes to watch TV.',
      'She likes to eat ice cream.',
    ],
    correct_index: 0,
    explanation_jp: '本文に「Coco likes to play in the park」とあります。公園で遊ぶのが好きです。',
    difficulty: 1,
    estimated_time_sec: 90,
    tags: ['reading', 'pet', 'detail'],
    copyright_safe: true,
    generated_quality_score: 0.90,
  },
  // R3-008 旅行
  {
    level: 'eiken-3',
    skill: 'reading',
    prompt_text: 'How long did Anna stay in the country town?',
    passage_text:
      'Anna lives in a big city, but last week she traveled to a small country town with her parents. They stayed in the town for three days. The town was very quiet. There were many trees and small rivers. Anna saw a lot of birds and fish. On the first day, she walked in the forest with her father. On the second day, the family had a picnic by the river. On the last day, Anna helped a farmer pick fresh tomatoes. Anna had a wonderful trip.',
    choices: [
      'Three days.',
      'One week.',
      'Two days.',
      'Five days.',
    ],
    correct_index: 0,
    explanation_jp: '本文に「They stayed in the town for three days」とあります。3日間滞在しました。',
    difficulty: 2,
    estimated_time_sec: 100,
    tags: ['reading', 'travel', 'duration'],
    copyright_safe: true,
    generated_quality_score: 0.88,
  },
  // R3-009 部活
  {
    level: 'eiken-3',
    skill: 'reading',
    prompt_text: 'Why does Sara practice tennis every day?',
    passage_text:
      'Sara joined the tennis club last month. At first, she could not hit the ball well. She felt sad and wanted to stop. But her coach said, "Don\'t give up, Sara. Practice every day, and you will get better." Sara listened to her coach. Now she practices for one hour every day after school. Last weekend, she played her first game and won. She was so happy. Next month, there will be a big tournament. Sara wants to do her best because she wants to make her coach proud.',
    choices: [
      'Because she wants to make her coach proud.',
      'Because her parents told her to.',
      'Because she likes the tennis uniform.',
      'Because she wants to be on TV.',
    ],
    correct_index: 0,
    explanation_jp: '本文に「Sara wants to do her best because she wants to make her coach proud」とあります。コーチを誇らしく思ってほしいからです。',
    difficulty: 2,
    estimated_time_sec: 100,
    tags: ['reading', 'club', 'reason'],
    copyright_safe: true,
    generated_quality_score: 0.86,
  },
  // R3-010 友達
  {
    level: 'eiken-3',
    skill: 'reading',
    prompt_text: 'What did Yuki and Ben do on Yuki\'s last day in Hanei Town?',
    passage_text:
      'Yuki and Ben were good friends at Sakura Elementary. They sat next to each other in class. They played soccer together every day after school. Last year, Yuki\'s family moved to another town because of her father\'s new job. Yuki and Ben were both very sad. On Yuki\'s last day in Hanei Town, they took a picture together in front of the school. They promised to write letters to each other. Now they send letters every month. Ben wants to visit Yuki\'s new town next summer.',
    choices: [
      'They took a picture in front of the school.',
      'They played soccer all day.',
      'They went to a restaurant.',
      'They wrote a long letter.',
    ],
    correct_index: 0,
    explanation_jp: '本文に「On Yuki\'s last day in Hanei Town, they took a picture together in front of the school」とあります。学校の前で写真を撮りました。',
    difficulty: 2,
    estimated_time_sec: 100,
    tags: ['reading', 'friendship', 'detail'],
    copyright_safe: true,
    generated_quality_score: 0.87,
  },
];

/**
 * 正答位置の均等分布化（DEC-011 / research-w1-llm-judge.md 準拠）
 *
 * 作問時は読みやすさのため correct_index = 0（先頭）に揃えていますが、
 * 学習者に出すときは position bias を避けるため 0/1/2/3 を均等にローテーションし、
 * 連続 3 回同じ正答禁止のルールを満たします。
 *
 * 決定論的（seed なし、index ベース）に並び替えるので、再投入のたびに同じ配置になります。
 */
function redistributeCorrectIndex(items: Problem[]): Problem[] {
  return items.map((p, i) => {
    const newCorrect = (i % 4) as 0 | 1 | 2 | 3;
    if (newCorrect === p.correct_index) return p;
    const choices = [...p.choices];
    const correctChoice = choices[p.correct_index] as string;
    const otherChoice = choices[newCorrect] as string;
    // 入れ替え: 元の correct を newCorrect 位置へ、newCorrect 位置のものを元位置へ
    choices[p.correct_index] = otherChoice;
    choices[newCorrect] = correctChoice;
    return { ...p, choices, correct_index: newCorrect };
  });
}

export default redistributeCorrectIndex(problems);


